# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14dd509321b9d5fafee74549518ed8548a0ae5e4f7b88ceef307c16cb57dc260691cc8dd9785deecb19f4df6fed5779caae36eb4047e2c3d41c86d04d5df610f

test:
  secret_key_base: b0034992a540b5953e5e17311beeb0e5bac7e62fffabecf3d9f1d19505d53349c213208b8cc3bd473134c093ddc4fb89f75a7d66b9f6cd090ed631b49063dda8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
